### PR TITLE
Accept enable

### LINKED ISSUE #64: Verilog backend validation broken
the Verilog backend should accept control that is just a single `enable`. right now, it only accepts programs that have a top-level `seq` and `enable`s.

### PR DESCRIPTION
**Pull request by tissue3**
Fix #64 ? (Also accept the outer most control with enable.)

### CODE REVIEW

File: calyx/src/backend/rtl/gen.rs [hunk 1]
```diff
@@ -23,6 +23,7 @@ impl Backend for RtlBackend {
                         }
                     }
                 }
+                Control::Enable { .. } => (),
```
Comment (rachitnigam) [inline calyx/src/backend/rtl/gen.rs]: Is this just to accept the case when we have no top-level `seq` and just a singular `enable`?

Comment (tissue3) [reply calyx/src/backend/rtl/gen.rs]: Yes. I saw issue #65 and changed it

File: calyx/README.md [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+  - [passes/](src/passes/) (optimisation passes)
+  - [backend/](src/backend/) (Verilog file generation)
+
+- [examples](examples/) (example files)
+
+- [primitives/](primitives) (libraries)
+
+  
+
+## Makefile
```
Comment (rachitnigam) [inline calyx/README.md]: It is worth mentioning that this is the Makefile under `calyx`. There is also a Makefile in the repo root that has the same targets.

**Comment by rachitnigam** [comment]
Looks good, Thanks! It is worth pointing out that you'd want to do most things within the `calyx` directory and not the repository root. Maybe we should re-org the repo and archive the old stuff.
