### PR TITLE
Frontend Redesign

### LINKED ISSUE #154: Don't index using Id
A bunch of data structures in `structure.rs` use `Id` or `Option<Id>` as index values. We should make them take strings instead since copying `Id` everyone is neither necessary nor useful since they contain extra information like spans.

### LINKED ISSUE #199: Redesigning Programmatic Interface
We've implemented a bunch of things and learned some things about the kind of things that the programmatic interface needs to be able to do.

Let's discuss our requirements and possible choices and implement things. There is a danger with discussions like these to spin out into abstract philosophizing without any action so let's put a **hard deadline of next Thursday (09/03)** so close this conversation and start implementing.

### Requirements

A programmatic interface has two requirements: analysis and manipulation. Here are some examples of things that each of these entail.

#### Analysis Tasks

In general, these seems like things that are best accomplished using a graph representation.

- Get all reads from a cell.
  - Get all reads from a port in a cell.
  - **NOTE**: Reads from ports in a guard are not currently considered as reads.
- Get all writes to a cell/port.
- Get all reads/writes in a group.

#### Manipulation Tasks

These seem like these would be best accomplished using some form of "structural" representation of the AST: Something like a list of assignments and cells.

- Create a new guarded assignment statement in a group.
  - In the current implementation, when we create a assignment it fells like we're manipulating a graph. It seems that creation of and manipulation should not be tied to the graph representation.
- Change a guard/destination port/source port in an assignment.

#### Bonus: Sharing Information

We've not yet built passes that share information between each other. Perhaps this is best accomplished as separate data structures but those would like either like graphs or hash maps or something.

#### Together, at last

The hard part of coming with a representation is that most passes perform both analysis and manipulation.
For example, the inlining pass needs to collect all reads to a hole (analysis), create a new expression, and inline the expression into all the uses (manipulation).

### Possible designs

1. [LNAST](https://woset-workshop.github.io/PDFs/2019/a3.pdf): It uses two representations at the same time. One that is a graph and another that is structural.
2. LLVM: I don't have the best idea about this. Maybe @sampsyo can add some thoughts?

### LINKED ISSUE #201: Use vast for the Verilog backend
The verilog backend currently generates strings. Lets switch it to use Luis's verilog ast library: [https://github.com/vegaluisjose/vast](https://github.com/vegaluisjose/vast)

### LINKED ISSUE #229: Example and tutorial programs should be tested
So that they don't get out of date.

### LINKED ISSUE #238: Refactoring static timing compilation for while control
The `while` control compilation in the static timing pass has two massive branches---one to handle combinational tests and one to handle other tests. We should refactor them after resolving #207.

### LINKED ISSUE #242: [papercut] inliner cycles cause stack overflow
If you write a program that causes the inliner to run forever, the only error you get is a stack overflow.

We should be smarter about detecting cycles where a hole includes itself in its guard.

Example:
```
import "primitives/std.lib";

component main() -> () {
  cells {}

  wires {
    group A {
      A[done] = A[go] ? 1'b1;
    }
    group B {
      B[done] = B[go] ? 1'b1;
    }
  }
  control {
    seq {
      A; B;
    }
  }
}
```
This has a cycle because `compile_control` generates the following code:
```
import "primitives/std.lib";
component main(go: 1, clk: 1) -> (done: 1) {
  cells {
    fsm0 = prim std_reg(2);
  }
  
  wires {
    group A<> {
      A[done] = A[go] ? 1'd1;
    }
    group B<> {
      B[done] = B[go] ? 1'd1;
    }
    group seq0<> {
      A[go] = (fsm0.out == 2'd0 & !(A[done]) & seq0[go]) ? 1'd1;
      fsm0.in = (fsm0.out == 2'd0 & A[done] & seq0[go]) ? 2'd1;
      fsm0.write_en = (fsm0.out == 2'd0 & A[done] & seq0[go]) ? 1'd1;
      B[go] = (fsm0.out == 2'd1 & !(B[done]) & seq0[go]) ? 1'd1;
      fsm0.in = (fsm0.out == 2'd1 & B[done] & seq0[go]) ? 2'd2;
      fsm0.write_en = (fsm0.out == 2'd1 & B[done] & seq0[go]) ? 1'd1;
      seq0[done] = fsm0.out == 2'd2 ? 1'd1;
    }
    seq0[go] = go;
    fsm0.write_en = fsm0.out == 2'd2 ? 1'd1;
    fsm0.in = fsm0.out == 2'd2 ? 2'd0;
    done = seq0[done] ? 1'd1;
  }
  
  control {
    seq0;
  }
}
```
where `A[go]` uses `!A[done]` in its guard and `A[done] = A[go]`.  

This is a slightly convoluted example, but I have come across this error several times.

### LINKED ISSUE #248: Inlining pass ignores X[go] in read positions in assignments.
```
import "primitives/std.lib";
component main() -> () {
  cells {
    x = prim std_reg(32);
    ret = prim std_reg(32);
    res9 = prim std_reg(32);
    const1 = prim std_const(32, 1);
    add2 = prim std_add(32);
    v = prim std_reg(32);
  }
  wires {
    group group10 {
      ret.in = res9.out;
      ret.write_en = group10[go];
      group10[done] = ret.done;
    }
    group group0 {
      v.in = add2.out;
      v.write_en = 1'd1;
      group0[done] = v.done;
      add2.left = x.out;
      add2.right = const1.out;
    }
  }
  control {
    seq {
      group0;
      group10;
    }
  }
}
```

Running ```fud e --from futil --to verilog frontends/relay-futil/tests/ifelse.expect``` on the code above gives the following error:

```
Stage 'futil' had a non-zero exit code.
--------------- stderr ---------------
thread 'main' panicked at 'internal error: entered unreachable code: Structure has a hole: group10', calyx/src/backend/verilog/gen.rs:331:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Supplementary comments from @rachitnigam about this issue: 

> Ah, I see what’s going on. The inlining pass (inliner.rs) only attempts to rewrite ret[go] that occur in the guard. It completely ignores all the ret[go] in read positions in assignments.
For example,
```
x.in = g1[go] ? 1'd1; // OK
x.in = g1[go]; // NOT OK
```
> This is exactly why the new representation needs to uniformly treat all uses of reads from ports.

### PR DESCRIPTION
**Pull request by rachitnigam**
Redesigns the FuTIL compiler's internal representation (IR). Because this representation is pervasively used, the PR touches basically everything. The high-level changes are:

- A new IR under `calyx::ir`.
  - `calyx::traversal` exposes a visitor-based infrastructure to traverse control programs.
  - `calyx::analysis` implements a graph-based analysis that calculates the reads-from and writes-to sets.
- Consolidation of frontend code.
  - Most of the AST defined in `lang::ast` is now under `frontend::ast`. The PR simplified some of the AST nodes.

## TODO
- [ ] ~Port `merge-assigns` pass.~ Do after merging this PR.
- [x] Port `externalize` pass.
- [x] go/done/clk insertion for components
#### Backend
- [x] Make the Verilog backend work again.
- [ ] Make the pretty-printer generate the same code.
#### Frontend
- [x] Make the pass manager infrastructure work again.
#### IR
- [x] Attach namegenerator to contexts.
- [x] Figure out how to expose components when they are attached to builders.
#### Cleanup
- [x] Delete `calyx/src/lang`.

Fixes #229. Fixes #248. Fixes #238. Fixes #199. Fixed #154. Fixes #242. Fixed #201. Closes #241.

### CODE REVIEW

**Comment by rachitnigam** [comment]
In order to expedite this merge, `merge-assigns` will be implemented in a separate PR.

File: calyx/src/ir/from_ast.rs [hunk 1]
```diff
@@ -44,9 +44,16 @@ pub fn ast_to_ir(
...
+        let mut sig = comp.signature.clone();
+        sig.inputs.push(ast::Portdef {
+            name: "go".into(),
+            width: 1,
+        });
+        sig.outputs.push(ast::Portdef {
+            name: "done".into(),
+            width: 1,
+        });
+        sig_ctx.comp_sigs.insert(comp.name.clone(), sig);
```
Comment (rachitnigam) [inline calyx/src/ir/from_ast.rs:56]: This is incorrect. See the `Component::new` function to see the names of all the ports generated. I would recommend creating a `pub(super)` method that returns the extended port list and use it in both `Component::new` and this function.

**Comment by rachitnigam** [comment]
All correctness tests are passing with this version of Vast: https://github.com/vegaluisjose/vast/pull/6. Cleanup remaining expectation tests carefully and then we merge.

**Comment by rachitnigam** [comment]
Verilog backend code generation is non-deterministic. @sgpthomas please fix.

**Comment by rachitnigam** [comment]
Post merge cleanup actions:
- [ ] Cleanup guard generation
- [ ] Port merge-assigns
- [ ] Make verilog backend generation deterministic.
